name: PostgreSQL Service Check

on: [push, workflow_dispatch]

jobs:
  test-postgres-service:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL service to be ready
        run: |
          echo "Waiting for PostgreSQL service to be ready..."
          for i in `seq 1 10`; do
            nc -z localhost 5432 && break
            echo "PostgreSQL not yet ready, waiting 1 more second..."
            sleep 1
          done
          nc -z localhost 5432 || { echo "PostgreSQL service did not become ready in time!"; exit 1; }
          echo "PostgreSQL service is ready!"

      - name: Verify PostgreSQL connection
        run: |
          # Install postgres client to connect and verify
          sudo apt-get update
          sudo apt-get install -y postgresql-client

          # Attempt to connect to the database, providing password via PGPASSWORD environment variable
          PGPASSWORD=${{ services.postgres.env.POSTGRES_PASSWORD }} psql \
            -h localhost \
            -p 5432 \
            -U ${{ services.postgres.env.POSTGRES_USER }} \
            -d ${{ services.postgres.env.POSTGRES_DB }} \
            -c "\conninfo" || { echo "Failed to connect to PostgreSQL!"; exit 1; }
          echo "Successfully connected to PostgreSQL database."
